import * as THREE from 'three';
import { GLTFLoader } from './vendor/GLTFLoader.js';

// All visible rolling stock originates from the licensed WAP-7 GLB; livery and consist variation are visual only.
export function initAuroraScene(host, ready){
  if(!host || !window.WebGLRenderingContext) throw new Error('WebGL unavailable');
  const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;host.append(renderer.domElement);
  const overlay=host.parentElement;overlay.insertAdjacentHTML('beforeend','<div class="three-loading">AURORA 3D ENGINE<br><small>Loading licensed rolling stock and topology…</small></div><div class="train-label"><span>TRAIN 12951</span><strong>110 km/h</strong><small>RISK: LOW</small></div>');const loading=overlay.querySelector('.three-loading'),label=overlay.querySelector('.train-label');
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x153038);scene.fog=new THREE.Fog(0x153038,90,290);const camera=new THREE.PerspectiveCamera(43,1,.1,600);camera.position.set(48,28,56);scene.add(new THREE.HemisphereLight(0xd8eff4,0x1c2922,2));const sun=new THREE.DirectionalLight(0xffefcf,3.2);sun.position.set(-55,65,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(500,500),new THREE.MeshStandardMaterial({color:0x284238,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
  const railMat=new THREE.MeshStandardMaterial({color:0xbdcbd0,metalness:.92,roughness:.23}), sleeperMat=new THREE.MeshStandardMaterial({color:0x4d4338,roughness:.95}), ballastMat=new THREE.MeshStandardMaterial({color:0x58635b,roughness:1}),steel=new THREE.MeshStandardMaterial({color:0x668083,metalness:.72,roughness:.35});
  const main=new THREE.CatmullRomCurve3([[-35,0,104],[-24,0,62],[-8,0,18],[6,0,-30],[20,0,-78],[35,0,-126]].map(v=>new THREE.Vector3(...v)),false,'centripetal');
  const tracks=[-4,0,4].map(offset=>new THREE.CatmullRomCurve3(Array.from({length:101},(_,i)=>{const u=i/100,p=main.getPointAt(u),t=main.getTangentAt(u).setY(0).normalize();return p.add(new THREE.Vector3(-t.z,0,t.x).multiplyScalar(offset));}),false,'centripetal'));
  // The alternate path shares the west main line, crosses at the physical junction, then joins the centre line.
  const eastAlternate=new THREE.CatmullRomCurve3([tracks[0].getPointAt(0),tracks[0].getPointAt(.22),tracks[0].getPointAt(.42),tracks[0].getPointAt(.48).lerp(tracks[1].getPointAt(.58),.5),tracks[1].getPointAt(.58),tracks[1].getPointAt(.78),tracks[1].getPointAt(1)],false,'centripetal');
  function addTrack(curve){const length=curve.getLength();[-.835,.835].forEach(o=>{const rail=new THREE.TubeGeometry(offsetCurve(curve,o),180,.07,6,false);scene.add(new THREE.Mesh(rail,railMat));});for(let d=0;d<length;d+=.78){const u=curve.getUtoTmapping(0,d),p=curve.getPointAt(u),t=curve.getTangentAt(u).setY(0).normalize(),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,1),t);const bed=new THREE.Mesh(new THREE.BoxGeometry(4.2,.2,.78),ballastMat);bed.position.copy(p).setY(-.02);bed.quaternion.copy(q);bed.receiveShadow=true;scene.add(bed);const sleeper=new THREE.Mesh(new THREE.BoxGeometry(2.8,.15,.22),sleeperMat);sleeper.position.copy(p).setY(.1);sleeper.quaternion.copy(q);sleeper.receiveShadow=true;scene.add(sleeper);}}
  function offsetCurve(curve,off){return new THREE.CatmullRomCurve3(Array.from({length:101},(_,i)=>{const u=i/100,p=curve.getPointAt(u),t=curve.getTangentAt(u).setY(0).normalize();return p.add(new THREE.Vector3(-t.z,0,t.x).multiplyScalar(off));}),false,'centripetal');}
  tracks.forEach(addTrack);
  // Connected crossovers at each end; these are visible topology, never random decorative rails.
  [[.22,0,1],[.75,1,2]].forEach(([u,a,b])=>{const pa=tracks[a].getPointAt(u),pb=tracks[b].getPointAt(Math.min(.98,u+.11));const c=new THREE.QuadraticBezierCurve3(pa,pa.clone().lerp(pb,.5).add(new THREE.Vector3(0,0,5)),pb);[-.835,.835].forEach(o=>scene.add(new THREE.Mesh(new THREE.TubeGeometry(offsetCurve(c,o),28,.07,6,false),railMat)));});
  function signal(curve,d,id){const u=curve.getUtoTmapping(0,d),p=curve.getPointAt(u),t=curve.getTangentAt(u).setY(0).normalize(),n=new THREE.Vector3(-t.z,0,t.x);const group=new THREE.Group(),mast=new THREE.Mesh(new THREE.CylinderGeometry(.09,.13,5,8),steel),lamp=new THREE.Mesh(new THREE.SphereGeometry(.24,12,8),new THREE.MeshStandardMaterial({color:0x54e0a2,emissive:0x167a51,emissiveIntensity:2}));mast.position.y=2.5;lamp.position.y=4.4;group.position.copy(p).addScaledVector(n,2.8);group.add(mast,lamp);scene.add(group);return {id,lamp};}
  const signalObjects={S204:signal(tracks[0],72,'S204'),S311:signal(tracks[1],125,'S311'),S402:signal(tracks[2],166,'S402')};
  for(let d=18;d<200;d+=32){const p=tracks[1].getPointAt(tracks[1].getUtoTmapping(0,d)),mast=new THREE.Mesh(new THREE.CylinderGeometry(.07,.1,7,8),steel);mast.position.copy(p).add(new THREE.Vector3(5,3.5,0));scene.add(mast);}
  // A station precinct belongs beside, not across, the running rails.  The canopy
  // is deliberately offset from the outer track clearance envelope.
  const station=new THREE.Group(), stationPoint=tracks[2].getPointAt(.46), stationTangent=tracks[2].getTangentAt(.46).setY(0).normalize(), stationNormal=new THREE.Vector3(-stationTangent.z,0,stationTangent.x);
  const platform=new THREE.Mesh(new THREE.BoxGeometry(48,.55,4),new THREE.MeshStandardMaterial({color:0x717c78,roughness:.85}));platform.position.copy(stationPoint).addScaledVector(stationNormal,5.2).setY(.18);platform.quaternion.setFromUnitVectors(new THREE.Vector3(1,0,0),stationTangent);station.add(platform);
  for(let i=-18;i<20;i+=9){const column=new THREE.Mesh(new THREE.CylinderGeometry(.13,.13,4,8),steel);column.position.copy(platform.position).addScaledVector(stationTangent,i).addScaledVector(stationNormal,.9).setY(2.2);station.add(column);}scene.add(station);
  // Route-zone scenery: forest approaches, station precinct, bridge, crossing, tunnel portal and electrification.
  const foliage=new THREE.MeshStandardMaterial({color:0x1d5637,roughness:1}), trunkMat=new THREE.MeshStandardMaterial({color:0x4a3423,roughness:1}), concrete=new THREE.MeshStandardMaterial({color:0x61716d,roughness:.8});
  function treeAt(curve,u,side){const p=curve.getPointAt(u),t=curve.getTangentAt(u).setY(0).normalize(),n=new THREE.Vector3(-t.z,0,t.x),g=new THREE.Group(),trunk=new THREE.Mesh(new THREE.CylinderGeometry(.16,.23,2.5,7),trunkMat),crown=new THREE.Mesh(new THREE.ConeGeometry(1.45,4.6,9),foliage);trunk.position.y=1.25;crown.position.y=4;g.position.copy(p).addScaledVector(n,side);g.add(trunk,crown);scene.add(g);}
  [.05,.09,.13,.17,.7,.74,.78,.82,.88].forEach((u,i)=>{treeAt(tracks[i%3],u,i%2?10:-10);treeAt(tracks[(i+1)%3],u,i%2?14:-14);});
  const bridge=new THREE.Mesh(new THREE.BoxGeometry(32,1.2,12),concrete);bridge.position.copy(tracks[1].getPointAt(.69)).setY(-.35);bridge.rotation.y=-.58;bridge.receiveShadow=true;scene.add(bridge);
  const portal=new THREE.Mesh(new THREE.BoxGeometry(16,9,1.4),concrete);portal.position.copy(tracks[1].getPointAt(.93)).setY(4);portal.rotation.y=-.58;scene.add(portal);
  const crossing=tracks[0].getPointAt(.31),road=new THREE.Mesh(new THREE.BoxGeometry(18,.12,6),new THREE.MeshStandardMaterial({color:0x30383a,roughness:.95}));road.position.copy(crossing).setY(.16);road.rotation.y=.72;scene.add(road);
  for(let u=.04;u<.98;u+=.12){const p=tracks[1].getPointAt(u),pole=new THREE.Mesh(new THREE.CylinderGeometry(.06,.09,8,8),steel);pole.position.copy(p).add(new THREE.Vector3(5,4,0));scene.add(pole);}
  function sprite(text,color='#ecf9fb'){const c=document.createElement('canvas');c.width=512;c.height=88;const x=c.getContext('2d');x.fillStyle='#071216e8';x.fillRect(0,0,512,88);x.strokeStyle=color;x.lineWidth=4;x.strokeRect(2,2,508,84);x.fillStyle=color;x.font='bold 35px Arial';x.textAlign='center';x.fillText(text,256,57);const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;return tx;}
  function normalize(source,length,livery){const model=source.clone(true),box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),scale=length/Math.max(size.x,size.z);model.scale.setScalar(scale);const after=new THREE.Box3().setFromObject(model),center=after.getCenter(new THREE.Vector3());model.position.sub(center);model.position.y-=after.min.y;model.traverse(n=>{if(n.isMesh){n.castShadow=n.receiveShadow=true;n.material=n.material.clone();if(n.material.color)n.material.color.offsetHSL(livery,.05,0);}});return model;}
  const livery=[0,.06,-.08,.12,-.14,.18],cars=new Map();let data={trains:[],signals:{},phase:'normal',selected:'12951'},follow=false;
  function buildFleet(gltf){data.trains.forEach((t,i)=>{const group=new THREE.Group(),count=t.type==='Locomotive'?1:t.type==='Freight'?4:3;for(let c=0;c<count;c++){const car=normalize(gltf.scene,c?16:20,c===0?livery[i%livery.length]:-.02);car.position.z=-c*16.5;group.add(car);}const plate=new THREE.Sprite(new THREE.SpriteMaterial({map:sprite(t.number,'#f2cc70'),transparent:true,depthTest:false}));plate.scale.set(4.2,.72,1);plate.position.set(0,2.15,.3);group.add(plate);scene.add(group);cars.set(t.number,group);});ready?.();loading.remove();}
  // The control world is a deterministic 220 m streaming corridor: simulation
  // distance may grow forever while geometry is recycled around the observer.
  function position(){data.trains.forEach(t=>{const group=cars.get(t.number);if(!group)return;group.visible=Boolean(t.active)&&!t.completed;if(!group.visible)return;const curve=t.route==='EAST_ALTERNATE'?eastAlternate:tracks[t.track%3],len=curve.getLength(),localDistance=((t.distance%220)+220)%220,u=curve.getUtoTmapping(0,localDistance/220*len),p=curve.getPointAt(u),tangent=curve.getTangentAt(u).setY(0).normalize(),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,0,1),tangent);group.position.copy(p).setY(.38);group.quaternion.slerp(q,.25);});}
  document.addEventListener('aurora:state',e=>{data=e.detail||data;Object.entries(signalObjects).forEach(([id,obj])=>{const red=data.signals?.[id]==='RED';obj.lamp.material.color.setHex(red?0xff4141:0x54e0a2);obj.lamp.material.emissive.setHex(red?0xa40000:0x167a51);});});document.addEventListener('aurora:camera',e=>{follow=e.detail==='follow';});
  new GLTFLoader().load('/frontend/public/assets/trains/wap7/locomotive.glb',g=>buildFleet(g),undefined,e=>{loading.textContent='TRAIN ASSET LOAD FAILURE';loading.classList.add('asset-error');console.error(e);});
  const point=new THREE.Vector3(),target=new THREE.Vector3();function frame(){const rect=host.getBoundingClientRect();if(rect.width&&rect.height){renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();}position();const lead=cars.get(data.selected);if(lead){target.copy(lead.position).add(new THREE.Vector3(0,2,0));if(follow)camera.position.lerp(lead.position.clone().add(new THREE.Vector3(17,9,17)),.04);camera.lookAt(target);point.copy(lead.position).add(new THREE.Vector3(0,5,0)).project(camera);label.style.transform=`translate(-50%,-100%) translate(${(point.x*.5+.5)*rect.width}px,${(-point.y*.5+.5)*rect.height}px)`;const train=data.trains.find(t=>t.number===data.selected);if(train){label.querySelector('span').textContent=`TRAIN ${train.number}`;label.querySelector('strong').textContent=`${Math.round(train.speed)} km/h`;label.querySelector('small').textContent=data.phase==='normal'?'RISK: LOW':'RISK: INTERVENING';label.className=`train-label ${data.phase==='normal'?'':'critical'}`;}}renderer.render(scene,camera);requestAnimationFrame(frame);}frame();
}
